import Fastify from "fastify";
import jwt from "@fastify/jwt";
import cors from "@fastify/cors";
import { Db, MongoClient } from "mongodb";
import { v4 as uuidv4 } from "uuid";
import crypto from "crypto";
import Anthropic from "@anthropic-ai/sdk";

declare module "@fastify/jwt" {
  interface FastifyJWT {
    payload: { sub: string; username: string; roles: ("admin" | "editor" | "viewer")[] };
    user: { sub: string; username: string; roles: ("admin" | "editor" | "viewer")[] };
  }
}

type RoomConfig = {
  roomId: string;
  campus?: string;
  building?: string;
  ip?: string;
  updatedAt: Date;
  updatedBy: string;
  version: number;
  [key: string]: unknown;
};

type RoomConfigDoc = {
  _id: string;
  config: RoomConfig;
};

const app = Fastify({ logger: true });

// CORS (needed for browser-based clients like the Angular portal)
// Register early so preflight OPTIONS always gets the right headers.
app.register(cors, {
  origin: true, // reflect request Origin (dev-friendly)
  methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
  allowedHeaders: ["Content-Type", "Authorization"],
});

const MONGO_URI =
  process.env.MONGO_URI ||
  "mongodb://avapp:avrocks@192.168.1.225:27017/avdb?authSource=avdb";

type TemplateDoc = {
  _id: string; // GUID generated by uuidv4
  name: string;
  icon: string;
  createdby: string;
  created: string;
  permission: string;
  config: Record<string, unknown>;
};

const client = new MongoClient(MONGO_URI);
let db: Db;
const roomConfigs = () => db.collection<RoomConfigDoc>("rooms");
const templates = () => db.collection<TemplateDoc>("templates");

const ROOM_SUMMARY_PROJECTION = {
  _id: 1,
  "config.campus": 1,
  "config.building": 1,
  "config.room": 1,
  "config.ip": 1,
  "config.roomType": 1,
  "config.version": 1,
  "config.updatedAt": 1,
  "config.updatedBy": 1,
  "config.sla": 1,
  "config.slaExpireAt": 1,
} as const;

type AppUser = {
  username: string;
  passwordHash: string;
  roles: ("admin" | "editor" | "viewer")[];
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  lastLoginAt?: Date | null;
};

type AppUserDoc = {
  _id: string; // GUID
  user: AppUser;
};
const users = () => db.collection<AppUserDoc>("users");

function hashPasswordScrypt(password: string): string {
  // Store as: scrypt:<saltHex>:<hashHex>
  const salt = crypto.randomBytes(16);
  const hash = crypto.scryptSync(password, salt, 32);
  return `scrypt:${salt.toString("hex")}:${hash.toString("hex")}`;
}

function verifyPasswordScrypt(password: string, stored: string): boolean {
  // stored: scrypt:<saltHex>:<hashHex>
  const parts = stored.split(":");
  if (parts.length !== 3) return false;

  const [algo, saltHex, hashHex] = parts;
  if (algo !== "scrypt" || !saltHex || !hashHex) return false;

  const salt = Buffer.from(saltHex, "hex");
  const expected = Buffer.from(hashHex, "hex");
  const actual = crypto.scryptSync(password, salt, expected.length);

  // timing safe compare
  return expected.length === actual.length && crypto.timingSafeEqual(actual, expected);
}

async function ensureUser(args: {
  username: string;
  password: string;
  roles: ("admin" | "editor" | "viewer")[];
}): Promise<void> {
  const { username, password, roles } = args;

  const existing = await users().findOne(
    { "user.username": username },
    { projection: { _id: 1 } as any }
  );

  if (existing) return;

  const now = new Date();
  const doc: AppUserDoc = {
    _id: uuidv4(),
    user: {
      username,
      passwordHash: hashPasswordScrypt(password),
      roles,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      lastLoginAt: null,
    },
  };

  await users().insertOne(doc);
  app.log.info({ username, roles }, "Bootstrapped default user");
}

async function ensureDefaultUsers(): Promise<void> {
  // For demos: defaults are provided if env vars are not set.
  // Set these in docker-compose for safer behavior.
  const adminUsername = process.env.BOOTSTRAP_ADMIN_USERNAME || "admin";
  const adminPassword = process.env.BOOTSTRAP_ADMIN_PASSWORD || "admin";

  const apiUsername = process.env.BOOTSTRAP_API_USERNAME || "api";
  const apiPassword = process.env.BOOTSTRAP_API_PASSWORD || "api";

  if (!process.env.BOOTSTRAP_ADMIN_PASSWORD) {
    app.log.warn(
      "BOOTSTRAP_ADMIN_PASSWORD is not set; using default 'admin'. Set env vars before production."
    );
  }
  if (!process.env.BOOTSTRAP_API_PASSWORD) {
    app.log.warn(
      "BOOTSTRAP_API_PASSWORD is not set; using default 'api'. Set env vars before production."
    );
  }

  await ensureUser({ username: adminUsername, password: adminPassword, roles: ["admin"] });
  await ensureUser({ username: apiUsername, password: apiPassword, roles: ["editor"] });
}

function normalizeClientIp(raw: string | undefined): string | undefined {
  if (!raw) return undefined;

  // If multiple IPs are present (x-forwarded-for), take the first
  const first = raw.split(",")[0]?.trim();
  if (!first) return undefined;

  // Strip IPv6-mapped IPv4 prefix (e.g. ::ffff:192.168.1.10)
  const noV6Map = first.startsWith("::ffff:") ? first.slice("::ffff:".length) : first;

  // If something includes a port like 192.168.1.10:12345, strip port
  const noPort =
    noV6Map.match(/^\d+\.\d+\.\d+\.\d+:/) ? noV6Map.split(":")[0] : noV6Map;

  return noPort;
}

function getClientIp(request: any): string | undefined {
  const xff = request.headers?.["x-forwarded-for"] as string | undefined;
  return normalizeClientIp(xff ?? request.ip);
}

async function requireAuth(request: any, reply: any): Promise<void> {
  try {
    await request.jwtVerify();
  } catch {
    reply.code(401).send({ error: "Unauthorized" });
  }
}

function requireAnyRole(roles: ("admin" | "editor" | "viewer")[]) {
  return async (request: any, reply: any): Promise<void> => {
    await requireAuth(request, reply);
    if (reply.sent) return;

    const userRoles: ("admin" | "editor" | "viewer")[] = request.user?.roles ?? [];
    const ok = roles.some((r) => userRoles.includes(r));
    if (!ok) {
      reply.code(403).send({ error: "Forbidden" });
    }
  };
}

function requireRole(role: "admin" | "editor" | "viewer") {
  return requireAnyRole([role]);
}

app.get("/health", async () => {
  return { status: "ok" };
});

app.post("/auth/login", async (request, reply) => {
  const body = request.body as any;
  const username = String(body?.username ?? "").trim();
  const password = String(body?.password ?? "");

  if (!username || !password) {
    return reply.code(400).send({ error: "Username and password required" });
  }

  const doc = await users().findOne({ "user.username": username });
  if (!doc) {
    return reply.code(401).send({ error: "Invalid credentials" });
  }

  if (!doc.user.isActive) {
    return reply.code(403).send({ error: "Account disabled" });
  }

  const ok = verifyPasswordScrypt(password, doc.user.passwordHash);
  if (!ok) {
    return reply.code(401).send({ error: "Invalid credentials" });
  }

  const now = new Date();
  await users().updateOne(
    { _id: doc._id },
    { $set: { "user.lastLoginAt": now, "user.updatedAt": now } }
  );

  const token = await reply.jwtSign({
    sub: doc._id,
    username: doc.user.username,
    roles: doc.user.roles,
  });

  return reply.send({
    token,
    user: { username: doc.user.username, roles: doc.user.roles },
  });
});

app.post("/auth/register", async (request, reply) => {
  const body = request.body as any;
  const username = String(body?.username ?? "").trim();
  const password = String(body?.password ?? "");

  // Optional requested role (viewer/editor only). Default to editor.
  const requestedRoleRaw = String(body?.role ?? "editor").toLowerCase();
  const role: "viewer" | "editor" = requestedRoleRaw === "viewer" ? "viewer" : "editor";

  if (!username || !password) {
    return reply.code(400).send({ error: "Username and password required" });
  }

  // Basic sanity limits (keeps junk out of DB)
  if (username.length < 3 || username.length > 50) {
    return reply.code(400).send({ error: "Username must be 3-50 characters" });
  }
  if (password.length < 8 || password.length > 200) {
    return reply.code(400).send({ error: "Password must be at least 8 characters" });
  }

  const existing = await users().findOne(
    { "user.username": username },
    { projection: { _id: 1 } as any }
  );
  if (existing) {
    return reply.code(409).send({ error: "Username already exists" });
  }

  const now = new Date();
  const doc: AppUserDoc = {
    _id: uuidv4(),
    user: {
      username,
      passwordHash: hashPasswordScrypt(password),
      roles: [role],
      isActive: true,
      createdAt: now,
      updatedAt: now,
      lastLoginAt: null,
    },
  };

  await users().insertOne(doc);

  // Auto-login on register (convenient for the web portal)
  const token = await reply.jwtSign({
    sub: doc._id,
    username: doc.user.username,
    roles: doc.user.roles,
  });

  return reply.code(201).send({
    token,
    user: { username: doc.user.username, roles: doc.user.roles },
  });
});

app.get("/rooms", async (request) => {
  const { campus, building } = request.query as {
    campus?: string;
    building?: string;
  };

  const filter: Record<string, unknown> = {};
  if (campus) filter["config.campus"] = campus;
  if (building) filter["config.building"] = building;

  const rooms = await roomConfigs()
    .find(filter, { projection: ROOM_SUMMARY_PROJECTION as any })
    .sort({ "config.campus": 1, "config.building": 1, "config.room": 1 })
    .toArray();

  return rooms;
});

app.get("/rooms/:roomId", async (request, reply) => {
  const { roomId } = request.params as { roomId: string };
  const room = await roomConfigs().findOne({ _id: roomId }, { projection: { _id: 1, config: 1 } });

  if (!room) {
    return reply.code(404).send({ error: "Room not found" });
  }

  return room;
});

app.get("/campuses/:campus/rooms", async (request) => {
  const { campus } = request.params as { campus: string };
  const rooms = await roomConfigs()
    .find({ "config.campus": campus }, { projection: ROOM_SUMMARY_PROJECTION as any })
    .sort({ "config.building": 1, "config.room": 1 })
    .toArray();
  return rooms;
});

app.get("/campuses/:campus/buildings/:building/rooms", async (request) => {
  const { campus, building } = request.params as { campus: string; building: string };
  const rooms = await roomConfigs()
    .find(
      { "config.campus": campus, "config.building": building },
      { projection: ROOM_SUMMARY_PROJECTION as any }
    )
    .sort({ "config.room": 1 })
    .toArray();
  return rooms;
});

app.get("/config/by-client-ip", async (request, reply) => {
  const clientIp = getClientIp(request);
  if (!clientIp) {
    return reply.code(400).send({ error: "Unable to determine client IP" });
  }

  const doc = await roomConfigs().findOne({ "config.ip": clientIp }, { projection: { _id: 1, config: 1 } });
  if (!doc) {
    return reply.code(404).send({ error: "No config found for client IP", ip: clientIp });
  }

  return doc;
});

async function upsertRoomConfig(args: {
  roomId: string;
  incoming: Record<string, unknown>;
  updatedBy: string;
}): Promise<{ roomId: string; version: number | null }> {
  const { roomId, incoming, updatedBy } = args;

  // Build the stored config: keep all incoming fields, but enforce roomId + metadata
  const config: RoomConfig = {
    ...(incoming as any),
    roomId,
    updatedAt: new Date(),
    updatedBy
  };

  await roomConfigs().updateOne(
    { _id: roomId },
    { $set: { _id: roomId, config } },
    { upsert: true }
  );

  return { roomId, version: (incoming as any)?.version ?? null };
}

// Create a new room config with a generated GUID (immutable identity)
app.post("/rooms", { preHandler: requireAnyRole(["admin", "editor"]) }, async (request, reply) => {
  const body = request.body as unknown;
  if (body === null || body === undefined || typeof body !== "object") {
    return reply.code(400).send({ success: false, error: "Body must be a JSON object" });
  }

  const incoming = body as Record<string, unknown>;

  const updatedBy = request.user.username;

  // Generate an immutable GUID that is NOT tied to campus/building/room naming
  const roomId = uuidv4();

  const result = await upsertRoomConfig({ roomId, incoming, updatedBy });

  return reply.code(201).send({ success: true, roomId: result.roomId, version: result.version });
});

// Backwards-compatible alias: treat PUT /rooms as create-with-guid as well
app.put("/rooms", { preHandler: requireAnyRole(["admin", "editor"]) }, async (request, reply) => {
  const body = request.body as unknown;
  if (body === null || body === undefined || typeof body !== "object") {
    return reply.code(400).send({ success: false, error: "Body must be a JSON object" });
  }

  const incoming = body as Record<string, unknown>;
  const updatedBy = request.user.username;

  const roomId = uuidv4();
  const result = await upsertRoomConfig({ roomId, incoming, updatedBy });

  return reply.code(201).send({ success: true, roomId: result.roomId, version: result.version });
});

app.put("/rooms/:roomId", { preHandler: requireAnyRole(["admin", "editor"]) }, async (request, reply) => {
  const { roomId } = request.params as { roomId: string };

  if (typeof roomId !== "string" || roomId.trim().length === 0) {
    return reply.code(400).send({ success: false, error: "roomId must be a non-empty string" });
  }

  const body = request.body as unknown;
  if (body === null || body === undefined || typeof body !== "object") {
    return reply.code(400).send({ success: false, error: "Body must be a JSON object" });
  }

  const incoming = body as Record<string, unknown>;

  const updatedBy = request.user.username;

  const result = await upsertRoomConfig({ roomId, incoming, updatedBy });
  return { success: true, roomId: result.roomId, version: result.version };
});

// ----- Streams -----

const MEDIAMTX_HOST = process.env.MEDIAMTX_HOST || "192.168.1.225";
const MEDIAMTX_WEBRTC_PORT = process.env.MEDIAMTX_WEBRTC_PORT || "8889";
const MEDIAMTX_HLS_PORT = process.env.MEDIAMTX_HLS_PORT || "8888";

app.get("/rooms/:roomId/streams", async (request, reply) => {
  const { roomId } = request.params as { roomId: string };
  const room = await roomConfigs().findOne({ _id: roomId }, { projection: { _id: 1, config: 1 } });

  if (!room) {
    return reply.code(404).send({ error: "Room not found" });
  }

  const devices = (room.config.Devices ?? {}) as Record<string, any>;
  const streams: { name: string; rtsp: string; webrtc: string; hls: string }[] = [];

  for (const [key, device] of Object.entries(devices)) {
    const rtspUrl: string | undefined = device.RtspUrl;
    if (!rtspUrl) continue;

    const pathName = `${roomId}/${key}`.toLowerCase().replace(/[^a-z0-9/_-]/g, "-");

    streams.push({
      name: device.FriendlyName ?? key,
      rtsp: rtspUrl,
      webrtc: `http://${MEDIAMTX_HOST}:${MEDIAMTX_WEBRTC_PORT}/${pathName}`,
      hls: `http://${MEDIAMTX_HOST}:${MEDIAMTX_HLS_PORT}/${pathName}`,
    });
  }

  return { roomId, streams };
});

app.post("/templates", { preHandler: requireAnyRole(["admin", "editor"]) }, async (request, reply) => {
  const body = request.body as any;
  if (!body?.name) return reply.code(400).send({ error: "name is required" });

  const doc: TemplateDoc = {
    _id: uuidv4(),
    name: body.name,
    icon: body.icon ?? "description",
    createdby: request.user.username,
    created: new Date().toISOString(),
    permission: body.permission ?? "private",
    config: body.config ?? {},
  };

  await templates().insertOne(doc);
  return reply.code(201).send({ success: true, _id: doc._id });
});

app.get("/templates", async () => {
  return templates()
    .find({}, { projection: { _id: 1, name: 1, icon: 1, createdby: 1, created: 1, permission: 1 } })
    .sort({ name: 1 })
    .toArray();
});

app.get("/templates/:id", async (request, reply) => {
  const { id } = request.params as { id: string };
  const doc = await templates().findOne({ _id: id });
  if (!doc) {
    return reply.code(404).send({ error: "Template not found" });
  }
  return doc;
});

// ── Admin: User Management ───────────────────────────────────────────────────

app.get("/admin/users", { preHandler: requireRole("admin") }, async () => {
  const docs = await users()
    .find({}, {
      projection: {
        _id: 1,
        "user.username": 1,
        "user.roles": 1,
        "user.isActive": 1,
        "user.createdAt": 1,
        "user.lastLoginAt": 1,
      } as any,
    })
    .sort({ "user.username": 1 })
    .toArray();

  return docs.map((d) => ({
    _id: d._id,
    username: d.user.username,
    roles: d.user.roles,
    isActive: d.user.isActive,
    createdAt: d.user.createdAt,
    lastLoginAt: d.user.lastLoginAt ?? null,
  }));
});

app.patch("/admin/users/:id/roles", { preHandler: requireRole("admin") }, async (request, reply) => {
  const { id } = request.params as { id: string };
  const body = request.body as any;
  const roles: ("admin" | "editor" | "viewer")[] = body?.roles;

  const validRoles = ["admin", "editor", "viewer"];
  if (!Array.isArray(roles) || roles.length === 0 || roles.some((r) => !validRoles.includes(r))) {
    return reply.code(400).send({ error: "roles must be a non-empty array of admin|editor|viewer" });
  }

  const res = await users().updateOne(
    { _id: id },
    { $set: { "user.roles": roles, "user.updatedAt": new Date() } }
  );
  if (res.matchedCount === 0) return reply.code(404).send({ error: "User not found" });

  return { success: true };
});

app.patch("/admin/users/:id/username", { preHandler: requireRole("admin") }, async (request, reply) => {
  const { id } = request.params as { id: string };
  const body = request.body as any;
  const username = String(body?.username ?? "").trim();

  if (!username || username.length < 3 || username.length > 50) {
    return reply.code(400).send({ error: "Username must be 3-50 characters" });
  }

  const existing = await users().findOne(
    { "user.username": username },
    { projection: { _id: 1 } as any }
  );
  if (existing && existing._id !== id) {
    return reply.code(409).send({ error: "Username already taken" });
  }

  const res = await users().updateOne(
    { _id: id },
    { $set: { "user.username": username, "user.updatedAt": new Date() } }
  );
  if (res.matchedCount === 0) return reply.code(404).send({ error: "User not found" });

  return { success: true };
});

app.patch("/admin/users/:id/password", { preHandler: requireRole("admin") }, async (request, reply) => {
  const { id } = request.params as { id: string };
  const body = request.body as any;
  const password = String(body?.password ?? "");

  if (!password || password.length < 8 || password.length > 200) {
    return reply.code(400).send({ error: "Password must be at least 8 characters" });
  }

  const passwordHash = hashPasswordScrypt(password);

  const res = await users().updateOne(
    { _id: id },
    { $set: { "user.passwordHash": passwordHash, "user.updatedAt": new Date() } }
  );
  if (res.matchedCount === 0) return reply.code(404).send({ error: "User not found" });

  return { success: true };
});

app.patch("/admin/users/:id/active", { preHandler: requireRole("admin") }, async (request, reply) => {
  const { id } = request.params as { id: string };
  const body = request.body as any;

  if (typeof body?.isActive !== "boolean") {
    return reply.code(400).send({ error: "isActive must be a boolean" });
  }

  const res = await users().updateOne(
    { _id: id },
    { $set: { "user.isActive": body.isActive, "user.updatedAt": new Date() } }
  );
  if (res.matchedCount === 0) return reply.code(404).send({ error: "User not found" });

  return { success: true };
});

app.delete("/rooms/:roomId", { preHandler: requireRole("admin") }, async (request, reply) => {
  const { roomId } = request.params as { roomId: string };

  const res = await roomConfigs().deleteOne({ _id: roomId });
  if (res.deletedCount === 0) {
    return reply.code(404).send({ error: "Room not found" });
  }

  return { success: true, roomId };
});

// ── Rick AI Chat ────────────────────────────────────────────────────────────

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

const RICK_SYSTEM_PROMPT = `You are Rick, an AI assistant embedded in an AV room configuration portal.
Your ONLY job is to help users edit AV room config settings by calling the provided tools.
You must ALWAYS respond with a short, friendly plain-text message describing what you did or why you can't do something.
You must NEVER answer general questions unrelated to room config.
If a request is unclear, ask a clarifying question.
When making changes, call the appropriate tool(s) and also include a text response explaining what you changed.`;

const RICK_TOOLS: Anthropic.Tool[] = [
  {
    name: "set_system_setting",
    description: "Set a top-level system setting field such as ip, roomType, sla, slaExpireAt, campus",
    input_schema: {
      type: "object" as const,
      properties: {
        field: { type: "string", description: "The field name, e.g. 'ip', 'roomType', 'sla'" },
        value: { type: "string", description: "The new value" },
      },
      required: ["field", "value"],
    },
  },
  {
    name: "set_source_field",
    description: "Set a field on a source, e.g. Label, Icon, IconSelected, Group, AutoStart, AutoShutdown, IsInvisible",
    input_schema: {
      type: "object" as const,
      properties: {
        sourceKey: { type: "string", description: "The source key, e.g. 'Source_1_Btn'" },
        field: { type: "string", description: "The field to set, e.g. 'Label', 'Icon', 'IsInvisible'" },
        value: { description: "The new value" },
      },
      required: ["sourceKey", "field", "value"],
    },
  },
  {
    name: "set_device_field",
    description: "Set a field on a device, e.g. FriendlyName, IpAddress, Make, Model, ControlType",
    input_schema: {
      type: "object" as const,
      properties: {
        deviceKey: { type: "string", description: "The device key, e.g. 'Proj-1'" },
        field: { type: "string", description: "The field to set, e.g. 'IpAddress', 'FriendlyName'" },
        value: { description: "The new value" },
      },
      required: ["deviceKey", "field", "value"],
    },
  },
  {
    name: "set_gain_field",
    description: "Set a field on a gain/audio channel, e.g. Label, Min, Max, IsInvisible, MuteLabel",
    input_schema: {
      type: "object" as const,
      properties: {
        gainKey: { type: "string", description: "The gain key, e.g. 'ProgGain'" },
        field: { type: "string", description: "The field to set" },
        value: { description: "The new value" },
      },
      required: ["gainKey", "field", "value"],
    },
  },
  {
    name: "set_page_field",
    description: "Set a field on a page, e.g. Title, Subtitle, Description, Image",
    input_schema: {
      type: "object" as const,
      properties: {
        pageId: { type: "string", description: "The page Id, e.g. 'HomePage'" },
        field: { type: "string", description: "The field to set" },
        value: { description: "The new value" },
      },
      required: ["pageId", "field", "value"],
    },
  },
  {
    name: "set_component_field",
    description: "Set a field on a component within a page, e.g. IsInvisible, or a property value",
    input_schema: {
      type: "object" as const,
      properties: {
        pageId: { type: "string", description: "The page Id containing the component" },
        componentKey: { type: "string", description: "The component key, e.g. 'RoomName'" },
        field: { type: "string", description: "The field to set, e.g. 'IsInvisible' or a property key like 'String'" },
        value: { description: "The new value" },
      },
      required: ["pageId", "componentKey", "field", "value"],
    },
  },
];

type RickMessage = { role: "user" | "assistant"; content: string };

app.post("/rick/chat", { preHandler: requireAuth }, async (request, reply) => {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return reply.code(503).send({ error: "AI assistant is not configured (missing ANTHROPIC_API_KEY)" });
  }

  const body = request.body as any;
  const messages: RickMessage[] = body?.messages ?? [];
  const config: Record<string, unknown> = body?.config ?? {};

  if (!messages.length) {
    return reply.code(400).send({ error: "messages array is required" });
  }

  // Inject current config as context in the first user message
  const configContext = `\nCurrent room config:\n${JSON.stringify(config, null, 2)}\n`;
  const apiMessages: Anthropic.MessageParam[] = messages.map((m, i) => ({
    role: m.role,
    content: i === 0 && m.role === "user" ? configContext + m.content : m.content,
  }));

  const response = await anthropic.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 1024,
    system: RICK_SYSTEM_PROMPT,
    tools: RICK_TOOLS,
    messages: apiMessages,
  });

  // Extract text and tool calls from response
  const text = response.content
    .filter((b): b is Anthropic.TextBlock => b.type === "text")
    .map((b) => b.text)
    .join(" ");

  const toolCalls = response.content
    .filter((b): b is Anthropic.ToolUseBlock => b.type === "tool_use")
    .map((b) => ({ name: b.name, input: b.input }));

  return { text, toolCalls };
});

const start = async () => {
  await client.connect();
  db = client.db("avdb");

  // JWT auth (required for write operations)
  await app.register(jwt, {
    secret: process.env.JWT_SECRET || "dev-secret-change-me",
  });

  // Indexes (idempotent)
  // `_id` is already unique by definition; no need for a unique index on config.roomId
  await roomConfigs().createIndex({ "config.ip": 1 });
  await roomConfigs().createIndex({ "config.campus": 1, "config.building": 1, "config.room": 1 });
  // Users index (idempotent)
  await users().createIndex({ "user.username": 1 }, { unique: true });
  // Templates index (idempotent — _id is the template name)
  await templates().createIndex({ _id: 1 });

  // Bootstrap default app users (idempotent)
  await ensureDefaultUsers();

  await app.listen({ port: 8080, host: "0.0.0.0" });
  console.log("API running on port 8080");
};

start();